.TH blog 1 "Aug 2009" "btools collection" "User Commands"
.SH NAME
blog \- Command line blog tool
.SH SYNOPSIS
.B blog
COMMAND [ARGUMENTS]
.br

.SH DESCRIPTION
Blog is a minimalist, extendible command line weblog and publishing tool. It is used by adding files to it and by setting up some usuable hooks.
.SH OPTIONS
.TP
-h   --help   
Help screen
.TP
add FILES  
Adds files to the weblog index
.TP
config (list [VARIABLE]|set VARIABLE VALUE|unset VARIABLES)  
Resp. lists, sets and unsets configuration variables.
.TP
help COMMANDS  
Output help for the given commands.
.TP
info OBJECTS  
Provides same functionality as multiple `meta OBJECT list` commands
.TP
init   
Initialize a new blog in the current directory
.TP
log   
Outputs the publication log of this index ordered on publication date.
.TP
meta OBJECT [(list|set VARIABLE VALUE|unset VARIABLES)]  
Shows, sets or unsets meta information on an object.
.TP
publish   
Execute the publish hooks
.TP
remove OBJECTS  rm OBJECTS  
Remove objects from the weblog index. Does not remove the file itself.
.TP
status   
Output the status of the files in the index

." Use .TP to indent.
.SH EXAMPLES
No examples available.

.SH SEE ALSO
cdbm(1), mkbm(1), btools(5)
.SH AUTHOR
Bart Spaans (bart.spaans@gmail.com)
