.TH blog 1 "Aug 2009" "btools collection" "User Commands"
.SH NAME
blog \- Command line blog tool
.SH SYNOPSIS

.SH DESCRIPTION
Command line blog tool
.SH OPTIONS
.TP
-h   --help   
Help screen
.TP
add FILES  
Adds files to the weblog index
.TP
config (list [VARIABLE]|set VARIABLE VALUE|unset VARIABLE)  
Resp. lists, sets and unsets configuration variables.
.TP
init   
Initialize a new blog in the current directory

." Use .TP to indent.
.SH EXAMPLES
No examples available.

.SH SEE ALSO
cdbm(1), mkbm(1), btools(5)
.SH AUTHOR
Bart Spaans (bart.spaans@gmail.com)
