.TH fill-template 1 "Sep 2009" "btools collection" "User Commands"
.SH NAME
fill-template \- Replaces variables with values in a given template.
.SH SYNOPSIS
.B fill-template
TEMPLATE [--VARIABLE VALUE]   Replaces every %VARIABLE% in TEMPLATE with VALUE.
.br

.SH DESCRIPTION
Can be used in one of blog's hooks as a very simple template language. Replaces all the %variables% with given values.
.SH OPTIONS
.TP
--help   
Output help

." Use .TP to indent.
.SH EXAMPLES
No examples available.

.SH SEE ALSO
cdbm(1), mkbm(1), btools(5)
.SH AUTHOR
Bart Spaans (bart@bookmark-tools.com)
