#!/usr/bin/env python

import sys

f = open("nav.html.template")

links = "<ul>\n"
for x in sys.argv[1:]:
	links += "\t<li><a href='%s' target='main'>%s</a></li>\n" % (x + ".html", x)

links += "</ul>"


template = f.read()
f.close()
result = template.replace("%links%", links)
print result

