#!/usr/bin/env python

import sys
import re

search = [ (re.compile(".*s.?([0-9]+).?e.?([0-9]+).*", re.IGNORECASE), 1), 
           (re.compile(".*(s|season|seizoen).?([0-9]+).?(e|episode|ep).?([0-9]+).*", re.IGNORECASE), 2),
           (re.compile(".*(s|season|seizoen).?([0-9]+).*", re.IGNORECASE), 2),
           ]


file = sys.argv[1]
bm = sys.argv[2]

res = []

for s, group in search:
    m = s.match(file)
    if m:
        res.append(m.group(group))


if len(res) == 1:
    r = int(res[0])
elif len(res) == 0:
    r = None
else:
    a = res[0]
    if all( a == x for x in res[1:]):
        r = a

if r is not None:
    print "-".join([bm, r])
else:
    print bm


