.TH bm 1 "August 2009" "btools" "User Commands"
.SH NAME
bm \- command line bookmarking tool
.SH SYNOPSIS
.B bm
[INDEX]
.br
.B bm
[TAG]
.br
.B bm
[TAG] --exec [COMMAND]
.br
.B bm
[ACTION] [ARGUMENTS]
.SH DESCRIPTION
.SH OPTIONS
%OPTIONS%
." Use .TP to indent.
.SH RETURN VALUES
Returns 0.
.SH FILES
Files associated with command
.SH EXAMPLES
%EXAMPLES%
.SH SEE ALSO
cdbm(1), mkbm(1), btools(5)
.SH BUGS
.SH AUTHOR
Bart Spaans (bart.spaans@gmail.com)
